// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zofecdiphpxlfgdabado.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZmVjZGlwaHB4bGZnZGFiYWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3ODQ1NDksImV4cCI6MjA3MzM2MDU0OX0.GB-4M8CcnBn1gWSembWNSwfyLgPRrd6pSdyw8WiuFnU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});